-- plug configuration
local plugpath = vim.fn.stdpath("data") .. '/site/autoload/plug.vim'
if not (vim.uv or vim.loop).fs_stat(plugpath) then
    -- detect os
    local your_os = require'oscall'.get_os()
    local link_to = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    local for_unix_base = function()
        local install_cmd = '\"curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs \"' .. link_to
        -- curl options
        --   -f, --fail    :
        --   -o, --output  : send output to the passed file instead of the stdout.
        --   -L, --location: Redirect to the alternative url if the indicated url 
        --                   has been move to. 
        io.popen("sh -c " .. install_cmd);
    end

    local for_windows = function()
        -- generated by Gemini...Sorry...
        -- Use -OutFile instead of piping to New-Item for a cleaner download
        -- We wrap the whole thing in 'powershell -NoProfile -Command'
        local ps_path = "$(@($env:XDG_DATA_HOME, $env:LOCALAPPDATA)[$null -eq $env:XDG_DATA_HOME])/nvim-data/site/autoload/plug.vim"
        local install_cmd = string.format(
            "powershell -NoProfile -Command \"$p='%s'; if(!(Test-Path (Split-Path $p))){ni (Split-Path $p) -ItemType Directory -Force}; iwr -UseBasicParsing '%s' -OutFile $p\"",
            ps_path,
            link_to
        )
        local handle = io.popen(install_cmd)
        if handle then
            local result = handle:read("*a")
            handle:close()
            print(result) -- Useful for debugging the output
        end
    end

    if your_os == 'Windows' then
        for_windows()
    else
        for_unix_base()
    end
end

local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug("")
Plug("scottmckendry/cyberdream.nvim")
Plug("mason-org/mason.nvim")
Plug("mason-org/mason-lspconfig.nvim")
Plug("keaising/im-select.nvim")
Plug("windwp/nvim-autopairs")
Plug("nvim-lua/plenary.nvim")
Plug("nvim-telescope/telescope.nvim")
Plug("xiyaowong/transparent.nvim")
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/cmp-path")
Plug("saadparwaiz1/cmp_luasnip")
Plug("L3MON4D3/LuaSnip")
Plug("nvim-lualine/lualine.nvim")
Plug("ThePrimeagen/harpoon")

vim.call('plug#end')
